spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: Admin1102@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect